name: Security Pipeline

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  security-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --force-reinstall -r requirements.txt

      - name: Run Semgrep (SAST)
        uses: returntocorp/semgrep-action@v1
        with:
          config: .semgrep/rules

      - name: Run pip-audit (dependency scan)
        if: ${{ always() }}
        run: |
          pip install pip-audit
          pip-audit
